// projects/ngx-kerusi-seatmap/src/lib/kerusi-seatmap/kerusi-section.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import {
  cssVar,
  DEFAULT_KERUSI_COLORS,
  elementFill,
  elementStyle,
  elementTextFill,
  KerusiSeatmapColors,
  occupantFillFor,
  occupantStrokeFor,
  PlacedElement,
  PlacedSeat,
  RenderSection,
  screenPath,
  seatBodyPath,
  SeatOccupantVariant,
  seatCoreFill,
  seatFill,
  seatOccupantPath,
  seatOccupantStroke,
  seatOccupantVariant,
  seatSelectedFrame,
  seatTextFill,
  seatWashFill,
  SectionLayout,
} from '@kerusiweb/core';

/**
 * Draws one Kerusi `Section` as a single `<svg>`.
 *
 * One SVG per section — rather than section groups inside a shared canvas — is
 * what makes per-section `aspectRatio` and mixed grid/freeform modes work: each
 * gets its own `viewBox` and its own intrinsic proportions, and CSS is free to
 * stack, wrap or column them. It also puts the section heading in real DOM,
 * where a screen reader can use it as a landmark.
 *
 * This component holds no state. It takes a placed layout and emits intent.
 */
@Component({
  selector: 'kerusi-section',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './kerusi-section.component.html',
  styleUrl: './kerusi-section.component.css',
})
export class KerusiSectionComponent {
  readonly section = input.required<RenderSection>();
  readonly layout = input.required<SectionLayout>();

  /** Currently selected seat ids. */
  readonly selection = input<ReadonlySet<string>>(new Set());
  /** The seat holding the section's single tab stop, if any. */
  readonly focusedSeatId = input<string | null>(null);
  /** Per-seat accessible names, keyed by seat id. */
  readonly ariaLabels = input<ReadonlyMap<string, string>>(new Map());

  readonly colors = input<Required<KerusiSeatmapColors>>(DEFAULT_KERUSI_COLORS);
  /** Whether an available seat may take its `SeatType.color` (§4.7). */
  readonly typeColors = input<boolean>(true);
  /** When false, seats render but do not respond to pointer or keyboard. */
  readonly interactive = input<boolean>(true);
  /**
   * CSS pixels per viewBox unit, at the section's natural size.
   *
   * Without a cap every section stretches to the full container width, so in a
   * four-tier theatre the narrow box row would draw seats several times the
   * size of the orchestra's. Capping each section at its own intrinsic width
   * keeps a seat the same size everywhere; a section too wide to fit still
   * scales down to the container.
   */
  readonly unitScale = input<number>(1);

  readonly seatActivate = output<string>();
  readonly seatFocused = output<string>();
  readonly seatKeydown = output<KeyboardEvent>();

  protected readonly viewBox = computed(() => `0 0 ${this.layout().width} ${this.layout().height}`);

  /** The section's natural width in CSS pixels; it never draws wider. */
  protected readonly naturalWidth = computed(() => this.layout().width * this.unitScale());

  protected isSelected(placed: PlacedSeat): boolean {
    return this.selection().has(placed.seat.id);
  }

  protected fill(placed: PlacedSeat): string {
    return seatFill(placed.seat, this.isSelected(placed), this.colors(), this.typeColors());
  }

  protected textFill(placed: PlacedSeat): string {
    return seatTextFill(placed.seat, this.isSelected(placed), this.colors(), this.typeColors());
  }

  protected backdrop(): string {
    return cssVar('backdrop', this.colors().backdrop);
  }

  // --- the seat glyph -------------------------------------------------------

  /** The seat's outline: square-ish front, tapered back — shape carries facing. */
  protected bodyPath(placed: PlacedSeat): string {
    return seatBodyPath(placed.x, placed.y, placed.width, placed.height);
  }

  /** `null` for an available or blocked seat — nothing to mark. */
  protected occupantVariant(placed: PlacedSeat): SeatOccupantVariant | null {
    return seatOccupantVariant(placed.seat, this.isSelected(placed));
  }

  /**
   * The box a seat's decorative marks are drawn to: the seat's own, or — when
   * it is selected — the core plate's, which is inset by the frame width.
   *
   * Everything over a selected seat sits on the core, so it all has to be
   * measured from the core. Drawing to the seat's box instead leaves the
   * occupant's hips crossing the frame, where a figure tinted `selectedBg`
   * lands on a frame filled `selectedBg` and reads as a hard nub. Since the
   * core is an exact scaled copy of the body (see {@link seatSelectedFrame}),
   * routing through here reproduces every clearance the mark had against the
   * body, scaled — so the frame width stays free to change.
   */
  private markBox(placed: PlacedSeat): { x: number; y: number; width: number; height: number } {
    if (!this.isSelected(placed)) {
      return placed;
    }
    const frame = seatSelectedFrame(placed.width, placed.height);
    return {
      x: placed.x + frame,
      y: placed.y + frame,
      width: placed.width - frame * 2,
      height: placed.height - frame * 2,
    };
  }

  /** The bright plate inside a selected seat's frame. */
  protected corePath(placed: PlacedSeat): string {
    const box = this.markBox(placed);
    return seatBodyPath(box.x, box.y, box.width, box.height);
  }

  protected coreFill(): string {
    return seatCoreFill(this.colors());
  }

  /** The dimming wash over a held or booked seat's type colour. */
  protected washFill(placed: PlacedSeat): string {
    // Only called for held/booked seats — see the template's @if.
    return seatWashFill(placed.seat.status as 'held' | 'booked', this.colors());
  }

  /** The occupant figure for a marked seat, sized to whatever it sits on. */
  protected occupantPath(placed: PlacedSeat): string {
    const box = this.markBox(placed);
    return seatOccupantPath(box.x, box.y, box.width, box.height);
  }

  protected occupantStroke(placed: PlacedSeat): number {
    const box = this.markBox(placed);
    return seatOccupantStroke(box.width, box.height);
  }

  // The wheelchair marker keeps the same relative corner it always had; only
  // the box it is relative to changes, so a selected seat's dot stays whole
  // instead of being bitten off by the frame.
  protected wheelchairCx(placed: PlacedSeat): number {
    const box = this.markBox(placed);
    return box.x + box.width * 0.82;
  }

  protected wheelchairCy(placed: PlacedSeat): number {
    const box = this.markBox(placed);
    return box.y + box.height * 0.18;
  }

  protected wheelchairRadius(placed: PlacedSeat): number {
    return this.markBox(placed).width * 0.13;
  }

  /**
   * A core-coloured outline behind a selected seat's number, painted under the
   * glyphs via `paint-order`.
   *
   * The label is centred on the occupant's shoulder line, so without this it is
   * `selectedBg` over a `selectedBg` silhouette — the figure, not the plate, is
   * what it actually has to contrast against. The halo also rescues a label too
   * long for the core, which would otherwise run onto the frame and vanish into
   * it.
   *
   * Bound here rather than in the stylesheet on purpose: a CSS
   * `var(--kerusi-selected-fg, …)` rule would carry the library default as its
   * fallback and silently skip the `[colors]` input tier, which only the
   * TypeScript side can resolve.
   */
  protected labelHalo(placed: PlacedSeat): string {
    return this.isSelected(placed) ? seatCoreFill(this.colors()) : 'none';
  }

  protected labelHaloWidth(placed: PlacedSeat): number {
    return this.isSelected(placed) ? placed.fontSize * 0.22 : 0;
  }

  /** Solid for selected/booked; `none` for held, which draws hollow instead. */
  protected occupantFill(variant: SeatOccupantVariant): string {
    return occupantFillFor(variant, this.colors());
  }

  protected occupantStrokeColor(variant: SeatOccupantVariant): string {
    return occupantStrokeFor(variant, this.colors());
  }

  /** The section's single tab stop; every other seat is reachable by arrow key. */
  protected tabIndex(placed: PlacedSeat): number {
    if (!this.interactive()) {
      return -1;
    }
    return placed.seat.id === this.focusedSeatId() ? 0 : -1;
  }

  protected ariaLabel(placed: PlacedSeat): string {
    return this.ariaLabels().get(placed.seat.id) ?? placed.seat.label;
  }

  protected seatClasses(placed: PlacedSeat): string {
    const seat = placed.seat;
    return [
      'kerusi-seat',
      `kerusi-seat--${seat.status}`,
      this.isSelected(placed) ? 'kerusi-seat--selected' : '',
      seat.selectable ? '' : 'kerusi-seat--unselectable',
      seat.accessibility?.wheelchairAccessible ? 'kerusi-seat--wheelchair' : '',
      seat.companions.length > 0 ? 'kerusi-seat--companion' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }

  /** SVG rotate() about the item's center; null when it does not rotate. */
  protected transform(item: PlacedSeat | PlacedElement): string | null {
    return item.rotation ? `rotate(${item.rotation} ${item.centerX} ${item.centerY})` : null;
  }

  /** Cancels the parent <g>'s rotation so the label stays upright and stays put. */
  protected counterRotate(item: PlacedSeat | PlacedElement): string | null {
    return item.rotation ? `rotate(${-item.rotation} ${item.centerX} ${item.centerY})` : null;
  }

  // --- elements -------------------------------------------------------------

  protected style(placed: PlacedElement) {
    return elementStyle(placed.element.kind);
  }

  protected elementFillOf(placed: PlacedElement): string {
    return elementFill(this.style(placed).tone, this.colors());
  }

  protected elementTextFillOf(placed: PlacedElement): string {
    return elementTextFill(this.style(placed).tone, this.colors());
  }

  protected screenPathOf(placed: PlacedElement): string {
    return screenPath(placed.x, placed.y, placed.width, placed.height);
  }

  /** The corner radius for a rectangular element; a stage reads as squarer. */
  protected radiusOf(placed: PlacedElement): number {
    return this.style(placed).shape === 'stage' ? 2 : Math.min(placed.height * 0.25, 6);
  }

  // --- interaction ----------------------------------------------------------

  protected onSeatClick(placed: PlacedSeat): void {
    if (this.interactive()) {
      this.seatActivate.emit(placed.seat.id);
    }
  }

  protected onSeatFocus(placed: PlacedSeat): void {
    if (this.interactive()) {
      this.seatFocused.emit(placed.seat.id);
    }
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (this.interactive()) {
      this.seatKeydown.emit(event);
    }
  }
}

<svg
  xmlns="http://www.w3.org/2000/svg"
  class="kerusi-section-svg"
  role="presentation"
  focusable="false"
  [style.--kerusi-focus-ring-input]="colors().focusRing"
  [attr.viewBox]="viewBox()"
  [style.max-width.px]="naturalWidth()"
  preserveAspectRatio="xMidYMid meet"
>
  <rect
    x="0"
    y="0"
    [attr.width]="layout().width"
    [attr.height]="layout().height"
    [style.fill]="backdrop()"
  />

  <!-- Elements first, so a screen or stage sits behind the seats it faces. -->
  @for (placed of layout().elements; track placed.element.id) {
    <g
      class="kerusi-element kerusi-element--{{ placed.element.kind }}"
      [attr.transform]="transform(placed)"
    >
      @switch (style(placed).shape) {
        @case ('screen') {
          <path [attr.d]="screenPathOf(placed)" [style.fill]="elementFillOf(placed)" />
        }
        @case ('void') {
          <rect
            class="kerusi-element__void"
            [attr.x]="placed.x"
            [attr.y]="placed.y"
            [attr.width]="placed.width"
            [attr.height]="placed.height"
            [style.stroke]="elementTextFillOf(placed)"
            fill="none"
          />
        }
        @default {
          <rect
            [attr.x]="placed.x"
            [attr.y]="placed.y"
            [attr.width]="placed.width"
            [attr.height]="placed.height"
            [attr.rx]="radiusOf(placed)"
            [style.fill]="elementFillOf(placed)"
          />
        }
      }
      @if (placed.element.label && style(placed).showLabel) {
        <text
          class="kerusi-element__label"
          text-anchor="middle"
          dominant-baseline="central"
          [attr.x]="placed.centerX"
          [attr.y]="placed.centerY"
          [attr.font-size]="placed.fontSize"
          [style.fill]="elementTextFillOf(placed)"
          [attr.transform]="counterRotate(placed)"
        >
          {{ placed.element.label }}
        </text>
      }
    </g>
  }

  @for (placed of layout().seats; track placed.seat.id) {
    <g
      [class]="seatClasses(placed)"
      role="button"
      [attr.tabindex]="tabIndex(placed)"
      [attr.aria-label]="ariaLabel(placed)"
      [attr.aria-pressed]="isSelected(placed)"
      [attr.aria-disabled]="!placed.seat.selectable"
      [attr.data-seat-id]="placed.seat.id"
      [attr.transform]="transform(placed)"
      (click)="onSeatClick(placed)"
      (focus)="onSeatFocus(placed)"
      (keydown)="onKeydown($event)"
    >
      @let variant = occupantVariant(placed);
      <!-- Tapered toward the back, square at the front, so which way the seat
           faces is legible from the outline alone. -->
      <path class="kerusi-seat__box" [attr.d]="bodyPath(placed)" [style.fill]="fill(placed)" />
      @if (variant === 'held' || variant === 'booked') {
        <!-- Colour stays the seat type's; a taken seat recedes under a wash
             instead, so the type colour still reads on a busy map. -->
        <path
          class="kerusi-seat__wash"
          [attr.d]="bodyPath(placed)"
          [style.fill]="washFill(placed)"
        />
      }
      @if (variant === 'selected') {
        <!-- Selection is the one state drawn from two tones: the body above is
             the frame, this is the bright core inside it. Whichever way the
             host page is themed, one of the two separates from it — which is
             why nothing here has to know about the page. -->
        <path class="kerusi-seat__core" [attr.d]="corePath(placed)" [style.fill]="coreFill()" />
      }
      @if (variant) {
        <!-- Deliberately not counter-rotated: the occupant leans with the
             seat. Solid = settled (yours, or sold); hollow = a hold still in
             progress. -->
        <path
          class="kerusi-seat__occupant kerusi-seat__occupant--{{ variant }}"
          [attr.d]="occupantPath(placed)"
          [attr.stroke-width]="occupantStroke(placed)"
          [style.fill]="occupantFill(variant)"
          [style.stroke]="occupantStrokeColor(variant)"
        />
      }
      <text
        class="kerusi-seat__label"
        text-anchor="middle"
        dominant-baseline="central"
        [attr.x]="placed.centerX"
        [attr.y]="placed.centerY"
        [attr.font-size]="placed.fontSize"
        [style.fill]="textFill(placed)"
        [style.stroke]="labelHalo(placed)"
        [attr.stroke-width]="labelHaloWidth(placed)"
        [attr.transform]="counterRotate(placed)"
      >
        {{ placed.seat.label }}
      </text>
      @if (placed.seat.accessibility?.wheelchairAccessible) {
        <!-- A corner marker, not a different fill: availability owns the fill. -->
        <circle
          class="kerusi-seat__wheelchair"
          [attr.cx]="wheelchairCx(placed)"
          [attr.cy]="wheelchairCy(placed)"
          [attr.r]="wheelchairRadius(placed)"
          [style.fill]="textFill(placed)"
        />
      }
    </g>
  }
</svg>

// projects/react/src/kerusi-section.tsx
import {
  cssVar,
  DEFAULT_KERUSI_COLORS,
  elementFill,
  elementStyle,
  elementTextFill,
  occupantFillFor,
  occupantStrokeFor,
  screenPath,
  seatBodyPath,
  seatCoreFill,
  seatFill,
  seatOccupantPath,
  seatOccupantStroke,
  seatOccupantVariant,
  seatSelectedFrame,
  seatTextFill,
  seatWashFill,
} from '@kerusiweb/core';
import type {
  KerusiSeatmapColors,
  PlacedElement,
  PlacedSeat,
  RenderSection,
  SectionLayout,
} from '@kerusiweb/core';
import type { CSSProperties, KeyboardEvent as ReactKeyboardEvent } from 'react';

export interface KerusiSectionProps {
  section: RenderSection;
  layout: SectionLayout;
  /** Currently selected seat ids. */
  selection?: ReadonlySet<string>;
  /** The seat holding the section's single tab stop, if any. */
  focusedSeatId?: string | null;
  /** Per-seat accessible names, keyed by seat id. */
  ariaLabels?: ReadonlyMap<string, string>;
  colors?: Required<KerusiSeatmapColors>;
  /** Whether an available seat may take its `SeatType.color` (§4.7). */
  typeColors?: boolean;
  /** When false, seats render but do not respond to pointer or keyboard. */
  interactive?: boolean;
  /**
   * CSS pixels per viewBox unit, at the section's natural size.
   *
   * Without a cap every section stretches to the full container width, so in a
   * four-tier theatre the narrow box row would draw seats several times the
   * size of the orchestra's. Capping each section at its own intrinsic width
   * keeps a seat the same size everywhere; a section too wide to fit still
   * scales down to the container.
   */
  unitScale?: number;
  onSeatActivate?: (seatId: string) => void;
  onSeatFocused?: (seatId: string) => void;
  onSeatKeyDown?: (event: ReactKeyboardEvent<SVGGElement>) => void;
  /** Called with each seat's `<g>` as it mounts and unmounts, for focus moves. */
  registerSeat?: (seatId: string, node: SVGGElement | null) => void;
}

const EMPTY_SELECTION: ReadonlySet<string> = new Set();
const EMPTY_LABELS: ReadonlyMap<string, string> = new Map();

/**
 * Draws one Kerusi `Section` as a single `<svg>`.
 *
 * One SVG per section — rather than section groups inside a shared canvas — is
 * what makes per-section `aspectRatio` and mixed grid/freeform modes work: each
 * gets its own `viewBox` and its own intrinsic proportions, and CSS is free to
 * stack, wrap or column them. It also puts the section heading in real DOM,
 * where a screen reader can use it as a landmark.
 *
 * This component holds no state. It takes a placed layout and reports intent.
 */
export function KerusiSection({
  layout,
  selection = EMPTY_SELECTION,
  focusedSeatId = null,
  ariaLabels = EMPTY_LABELS,
  colors = DEFAULT_KERUSI_COLORS,
  typeColors = true,
  interactive = true,
  unitScale = 1,
  onSeatActivate,
  onSeatFocused,
  onSeatKeyDown,
  registerSeat,
}: KerusiSectionProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className="kerusi-section-svg"
      role="presentation"
      focusable="false"
      viewBox={`0 0 ${layout.width} ${layout.height}`}
      preserveAspectRatio="xMidYMid meet"
      style={
        {
          // The focus ring's middle tier: the stylesheet reads this property,
          // so the `colors` prop can reach a rule it cannot otherwise see.
          '--kerusi-focus-ring-input': colors.focusRing,
          // The section's natural width in CSS pixels; it never draws wider.
          maxWidth: layout.width * unitScale,
        } as CSSProperties
      }
    >
      <rect
        x={0}
        y={0}
        width={layout.width}
        height={layout.height}
        style={{ fill: cssVar('backdrop', colors.backdrop) }}
      />

      {/* Elements first, so a screen or stage sits behind the seats it faces. */}
      {layout.elements.map((placed) => (
        <SectionElement key={placed.element.id} placed={placed} colors={colors} />
      ))}

      {layout.seats.map((placed) => (
        <SectionSeat
          key={placed.seat.id}
          placed={placed}
          selected={selection.has(placed.seat.id)}
          tabStop={placed.seat.id === focusedSeatId}
          ariaLabel={ariaLabels.get(placed.seat.id) ?? placed.seat.label}
          colors={colors}
          typeColors={typeColors}
          interactive={interactive}
          onSeatActivate={onSeatActivate}
          onSeatFocused={onSeatFocused}
          onSeatKeyDown={onSeatKeyDown}
          registerSeat={registerSeat}
        />
      ))}
    </svg>
  );
}

// --- seats ------------------------------------------------------------------

interface SeatProps {
  placed: PlacedSeat;
  selected: boolean;
  tabStop: boolean;
  ariaLabel: string;
  colors: Required<KerusiSeatmapColors>;
  typeColors: boolean;
  interactive: boolean;
  onSeatActivate?: (seatId: string) => void;
  onSeatFocused?: (seatId: string) => void;
  onSeatKeyDown?: (event: ReactKeyboardEvent<SVGGElement>) => void;
  registerSeat?: (seatId: string, node: SVGGElement | null) => void;
}

function SectionSeat({
  placed,
  selected,
  tabStop,
  ariaLabel,
  colors,
  typeColors,
  interactive,
  onSeatActivate,
  onSeatFocused,
  onSeatKeyDown,
  registerSeat,
}: SeatProps) {
  const seat = placed.seat;
  const variant = seatOccupantVariant(seat, selected);
  const box = markBox(placed, selected);
  const body = seatBodyPath(placed.x, placed.y, placed.width, placed.height);
  const textFill = seatTextFill(seat, selected, colors, typeColors);

  return (
    <g
      ref={(node: SVGGElement | null) => {
        registerSeat?.(seat.id, node);
      }}
      className={seatClasses(placed, selected)}
      role="button"
      tabIndex={interactive && tabStop ? 0 : -1}
      aria-label={ariaLabel}
      aria-pressed={selected}
      aria-disabled={!seat.selectable}
      data-seat-id={seat.id}
      transform={transform(placed) ?? undefined}
      onClick={interactive ? () => onSeatActivate?.(seat.id) : undefined}
      onFocus={interactive ? () => onSeatFocused?.(seat.id) : undefined}
      onKeyDown={interactive ? onSeatKeyDown : undefined}
    >
      {/* Tapered toward the back, square at the front, so which way the seat
          faces is legible from the outline alone. */}
      <path
        className="kerusi-seat__box"
        d={body}
        style={{ fill: seatFill(seat, selected, colors, typeColors) }}
      />
      {(variant === 'held' || variant === 'booked') && (
        /* Colour stays the seat type's; a taken seat recedes under a wash
           instead, so the type colour still reads on a busy map. */
        <path
          className="kerusi-seat__wash"
          d={body}
          style={{ fill: seatWashFill(variant, colors) }}
        />
      )}
      {variant === 'selected' && (
        /* Selection is the one state drawn from two tones: the body above is
           the frame, this is the bright core inside it. Whichever way the host
           page is themed, one of the two separates from it — which is why
           nothing here has to know about the page. */
        <path
          className="kerusi-seat__core"
          d={seatBodyPath(box.x, box.y, box.width, box.height)}
          style={{ fill: seatCoreFill(colors) }}
        />
      )}
      {variant && (
        /* Deliberately not counter-rotated: the occupant leans with the seat.
           Solid = settled (yours, or sold); hollow = a hold still in progress. */
        <path
          className={`kerusi-seat__occupant kerusi-seat__occupant--${variant}`}
          d={seatOccupantPath(box.x, box.y, box.width, box.height)}
          strokeWidth={seatOccupantStroke(box.width, box.height)}
          style={{
            fill: occupantFillFor(variant, colors),
            stroke: occupantStrokeFor(variant, colors),
          }}
        />
      )}
      <text
        className="kerusi-seat__label"
        textAnchor="middle"
        dominantBaseline="central"
        x={placed.centerX}
        y={placed.centerY}
        fontSize={placed.fontSize}
        /* The halo is a core-coloured outline behind a selected seat's number,
           painted under the glyphs via `paint-order`. The label is centred on
           the occupant's shoulder line, so without it the number is
           `selectedFg` over a `selectedBg` silhouette.

           Bound here rather than in the stylesheet on purpose: a CSS
           `var(--kerusi-selected-fg, …)` rule would carry the library default
           as its fallback and silently skip the `colors` prop tier, which only
           this side can resolve. */
        style={{ fill: textFill, stroke: selected ? seatCoreFill(colors) : 'none' }}
        strokeWidth={selected ? placed.fontSize * 0.22 : 0}
        transform={counterRotate(placed) ?? undefined}
      >
        {seat.label}
      </text>
      {seat.accessibility?.wheelchairAccessible && (
        /* A corner marker, not a different fill: availability owns the fill. */
        <circle
          className="kerusi-seat__wheelchair"
          cx={box.x + box.width * 0.82}
          cy={box.y + box.height * 0.18}
          r={box.width * 0.13}
          style={{ fill: textFill }}
        />
      )}
    </g>
  );
}

/**
 * The box a seat's decorative marks are drawn to: the seat's own, or — when it
 * is selected — the core plate's, which is inset by the frame width.
 *
 * Everything over a selected seat sits on the core, so it all has to be
 * measured from the core. Drawing to the seat's box instead leaves the
 * occupant's hips crossing the frame, where a figure tinted `selectedBg` lands
 * on a frame filled `selectedBg` and reads as a hard nub. Since the core is an
 * exact scaled copy of the body (see `seatSelectedFrame`), routing through here
 * reproduces every clearance the mark had against the body, scaled — so the
 * frame width stays free to change.
 */
function markBox(
  placed: PlacedSeat,
  selected: boolean,
): { x: number; y: number; width: number; height: number } {
  if (!selected) {
    return placed;
  }
  const frame = seatSelectedFrame(placed.width, placed.height);
  return {
    x: placed.x + frame,
    y: placed.y + frame,
    width: placed.width - frame * 2,
    height: placed.height - frame * 2,
  };
}

function seatClasses(placed: PlacedSeat, selected: boolean): string {
  const seat = placed.seat;
  return [
    'kerusi-seat',
    `kerusi-seat--${seat.status}`,
    selected ? 'kerusi-seat--selected' : '',
    seat.selectable ? '' : 'kerusi-seat--unselectable',
    seat.accessibility?.wheelchairAccessible ? 'kerusi-seat--wheelchair' : '',
    seat.companions.length > 0 ? 'kerusi-seat--companion' : '',
  ]
    .filter(Boolean)
    .join(' ');
}

// --- elements ---------------------------------------------------------------

function SectionElement({
  placed,
  colors,
}: {
  placed: PlacedElement;
  colors: Required<KerusiSeatmapColors>;
}) {
  const style = elementStyle(placed.element.kind);
  const fill = elementFill(style.tone, colors);
  const textFill = elementTextFill(style.tone, colors);

  return (
    <g
      className={`kerusi-element kerusi-element--${placed.element.kind}`}
      transform={transform(placed) ?? undefined}
    >
      {style.shape === 'screen' ? (
        <path d={screenPath(placed.x, placed.y, placed.width, placed.height)} style={{ fill }} />
      ) : style.shape === 'void' ? (
        <rect
          className="kerusi-element__void"
          x={placed.x}
          y={placed.y}
          width={placed.width}
          height={placed.height}
          style={{ stroke: textFill }}
          fill="none"
        />
      ) : (
        <rect
          x={placed.x}
          y={placed.y}
          width={placed.width}
          height={placed.height}
          /* A stage reads as squarer than an ordinary element. */
          rx={style.shape === 'stage' ? 2 : Math.min(placed.height * 0.25, 6)}
          style={{ fill }}
        />
      )}
      {placed.element.label && style.showLabel && (
        <text
          className="kerusi-element__label"
          textAnchor="middle"
          dominantBaseline="central"
          x={placed.centerX}
          y={placed.centerY}
          fontSize={placed.fontSize}
          style={{ fill: textFill }}
          transform={counterRotate(placed) ?? undefined}
        >
          {placed.element.label}
        </text>
      )}
    </g>
  );
}

/** SVG rotate() about the item's center; null when it does not rotate. */
function transform(item: PlacedSeat | PlacedElement): string | null {
  return item.rotation ? `rotate(${item.rotation} ${item.centerX} ${item.centerY})` : null;
}

/** Cancels the parent <g>'s rotation so the label stays upright and stays put. */
function counterRotate(item: PlacedSeat | PlacedElement): string | null {
  return item.rotation ? `rotate(${-item.rotation} ${item.centerX} ${item.centerY})` : null;
}
