// projects/ngx-kerusi-seatmap/src/lib/kerusi-seatmap/kerusi-legend.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  cssVar,
  DEFAULT_KERUSI_COLORS,
  formatMoney,
  KerusiSeatmapColors,
  occupantFillFor,
  occupantStrokeFor,
  readableOn,
  RenderLegendEntry,
  seatBodyPath,
  SeatOccupantVariant,
  seatCoreFill,
  seatOccupantPath,
  seatOccupantStroke,
  seatSelectedFrame,
  seatWashFill,
} from '@kerusiweb/core';

/** Which marks, beyond the body fill, a status swatch draws. */
type StatusKind = 'plain' | 'blocked' | SeatOccupantVariant;

/** One availability swatch in the legend's second block. */
interface StatusEntry {
  key: string;
  label: string;
  kind: StatusKind;
  /** The swatch body's fill. */
  fill: string;
}

/**
 * A key for a seat map: its seat types on one side, its availability states on
 * the other.
 *
 * This ships in the library rather than being left to each application because
 * the swatch colors must come from the *same* resolution path as the seat
 * fills — `SeatType.color` when the document supplies one, the theme's
 * available color when it does not. Re-deriving that in application code is how
 * a legend ends up disagreeing with the map it describes.
 *
 * It is opt-in: `<kerusi-seatmap [showLegend]="true">` renders it inline, or
 * use `<kerusi-legend>` directly to place it anywhere.
 */
@Component({
  selector: 'kerusi-legend',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './kerusi-legend.component.html',
  styleUrl: './kerusi-legend.component.css',
})
export class KerusiLegendComponent {
  /** From `RenderMap.legend`. */
  readonly legend = input.required<readonly RenderLegendEntry[]>();
  readonly locale = input<string>('en');
  readonly colors = input<Required<KerusiSeatmapColors>>(DEFAULT_KERUSI_COLORS);
  /** Whether an available seat takes its type color — mirrors the seatmap input. */
  readonly typeColors = input<boolean>(true);
  readonly showPrices = input<boolean>(true);
  /** Hide types no seat in the rendered map actually uses. */
  readonly hideUnusedTypes = input<boolean>(true);

  readonly headingSeatTypes = input<string>('Seat types');
  readonly headingAvailability = input<string>('Availability');

  protected readonly types = computed(() =>
    this.legend().filter((entry) => !this.hideUnusedTypes() || entry.seatCount > 0),
  );

  // Colour means seat type; shape means status (see `seatFill`'s doc comment).
  // Held and booked swatches share the plain "available" body colour — the
  // map's colour there is always whatever the seat's own type supplies, which
  // the legend has no single value for — and are told apart by their wash and
  // occupant figure instead, same as on the map.
  protected readonly statuses = computed<StatusEntry[]>(() => {
    const c = this.colors();
    const available = cssVar('availableBg', c.availableBg);
    return [
      { key: 'available', label: 'Available', kind: 'plain', fill: available },
      {
        key: 'selected',
        label: 'Selected',
        kind: 'selected',
        fill: cssVar('selectedBg', c.selectedBg),
      },
      { key: 'held', label: 'On hold', kind: 'held', fill: available },
      { key: 'booked', label: 'Booked', kind: 'booked', fill: available },
      { key: 'blocked', label: 'Blocked', kind: 'blocked', fill: cssVar('blockedBg', c.blockedBg) },
    ];
  });

  protected swatch(entry: RenderLegendEntry): string {
    return (this.typeColors() && entry.color) || cssVar('availableBg', this.colors().availableBg);
  }

  protected swatchText(entry: RenderLegendEntry): string {
    const typeColor = this.typeColors() && entry.color;
    // Mirrors `seatTextFill`: only a document-supplied color needs guessing at.
    return typeColor ? readableOn(typeColor) : cssVar('availableFg', this.colors().availableFg);
  }

  // --- status swatches -------------------------------------------------------
  //
  // Availability is now signalled by shape, not colour, so every status swatch
  // (bar "available" and "blocked") draws the same glyph the map does rather
  // than a flat square. A legend that showed only flat colour would teach a
  // cue the map no longer uses.

  /** The swatch's viewBox edge; the seat glyph is drawn to fill it. */
  protected readonly glyphSize = 16;

  protected readonly glyphBody = seatBodyPath(0, 0, this.glyphSize, this.glyphSize);

  /** The selected swatch's frame width, and the core it leaves inside itself. */
  private readonly glyphFrame = seatSelectedFrame(this.glyphSize, this.glyphSize);
  private readonly glyphCoreSize = this.glyphSize - this.glyphFrame * 2;
  protected readonly glyphCore = seatBodyPath(
    0,
    0,
    this.glyphSize,
    this.glyphSize,
    this.glyphFrame,
  );

  protected readonly glyphOccupant = seatOccupantPath(0, 0, this.glyphSize, this.glyphSize);
  protected readonly glyphOccupantStroke = seatOccupantStroke(this.glyphSize, this.glyphSize);

  /** The selected swatch's figure sits on the core, so it is drawn to the core. */
  private readonly glyphCoreOccupant = seatOccupantPath(
    this.glyphFrame,
    this.glyphFrame,
    this.glyphCoreSize,
    this.glyphCoreSize,
  );
  private readonly glyphCoreOccupantStroke = seatOccupantStroke(
    this.glyphCoreSize,
    this.glyphCoreSize,
  );

  protected occupantPathOf(variant: SeatOccupantVariant): string {
    return variant === 'selected' ? this.glyphCoreOccupant : this.glyphOccupant;
  }

  protected occupantStrokeWidthOf(variant: SeatOccupantVariant): number {
    return variant === 'selected' ? this.glyphCoreOccupantStroke : this.glyphOccupantStroke;
  }

  protected hasWash(kind: StatusKind): kind is 'held' | 'booked' {
    return kind === 'held' || kind === 'booked';
  }

  protected hasOccupant(kind: StatusKind): kind is SeatOccupantVariant {
    return kind === 'selected' || kind === 'held' || kind === 'booked';
  }

  protected washFillOf(kind: 'held' | 'booked'): string {
    return seatWashFill(kind, this.colors());
  }

  protected occupantFillOf(variant: SeatOccupantVariant): string {
    return occupantFillFor(variant, this.colors());
  }

  protected occupantStrokeOf(variant: SeatOccupantVariant): string {
    return occupantStrokeFor(variant, this.colors());
  }

  protected coreFill(): string {
    return seatCoreFill(this.colors());
  }

  protected price(entry: RenderLegendEntry): string {
    return entry.price ? formatMoney(entry.price, this.locale()) : '';
  }
}

<div class="kerusi-legend">
  @if (types().length) {
    <div class="kerusi-legend__block">
      <h4 class="kerusi-legend__heading">{{ headingSeatTypes() }}</h4>
      <ul class="kerusi-legend__list">
        @for (entry of types(); track entry.id) {
          <li class="kerusi-legend__item">
            <span
              class="kerusi-legend__swatch"
              aria-hidden="true"
              [style.background]="swatch(entry)"
              [style.color]="swatchText(entry)"
            ></span>
            <span class="kerusi-legend__label">{{ entry.label }}</span>
            @if (showPrices() && price(entry)) {
              <span class="kerusi-legend__price">{{ price(entry) }}</span>
            }
          </li>
        }
      </ul>
    </div>
  }

  <div class="kerusi-legend__block">
    <h4 class="kerusi-legend__heading">{{ headingAvailability() }}</h4>
    <ul class="kerusi-legend__list">
      @for (status of statuses(); track status.key) {
        <li class="kerusi-legend__item">
          <!-- Shape carries status now, so every swatch draws the seat glyph
               rather than a flat colour — a flat swatch would teach a cue the
               map itself no longer uses. -->
          <svg
            class="kerusi-legend__swatch kerusi-legend__swatch--glyph"
            aria-hidden="true"
            focusable="false"
            [attr.viewBox]="'0 0 ' + glyphSize + ' ' + glyphSize"
          >
            <path [attr.d]="glyphBody" [style.fill]="status.fill" />
            @if (hasWash(status.kind)) {
              <path [attr.d]="glyphBody" [style.fill]="washFillOf(status.kind)" opacity="0.5" />
            }
            @if (status.kind === 'selected') {
              <!-- Two tones, same as the map: the body above is the frame, this
                   is the core inside it. -->
              <path [attr.d]="glyphCore" [style.fill]="coreFill()" />
            }
            @if (hasOccupant(status.kind)) {
              <path
                [attr.d]="occupantPathOf(status.kind)"
                class="kerusi-legend__occupant kerusi-legend__occupant--{{ status.kind }}"
                [attr.stroke-width]="occupantStrokeWidthOf(status.kind)"
                [style.fill]="occupantFillOf(status.kind)"
                [style.stroke]="occupantStrokeOf(status.kind)"
              />
            }
          </svg>
          <span class="kerusi-legend__label">{{ status.label }}</span>
        </li>
      }
    </ul>
  </div>
</div>

// projects/react/src/kerusi-legend.tsx
import {
  cssVar,
  DEFAULT_KERUSI_COLORS,
  formatMoney,
  occupantFillFor,
  occupantStrokeFor,
  readableOn,
  seatBodyPath,
  seatCoreFill,
  seatOccupantPath,
  seatOccupantStroke,
  seatSelectedFrame,
  seatWashFill,
} from '@kerusiweb/core';
import type { KerusiSeatmapColors, RenderLegendEntry, SeatOccupantVariant } from '@kerusiweb/core';

/** Which marks, beyond the body fill, a status swatch draws. */
type StatusKind = 'plain' | 'blocked' | SeatOccupantVariant;

/** One availability swatch in the legend's second block. */
interface StatusEntry {
  key: string;
  label: string;
  kind: StatusKind;
  /** The swatch body's fill. */
  fill: string;
}

export interface KerusiLegendProps {
  /** From `RenderMap.legend`. */
  legend: readonly RenderLegendEntry[];
  locale?: string;
  colors?: Required<KerusiSeatmapColors>;
  /** Whether an available seat takes its type color — mirrors the seatmap prop. */
  typeColors?: boolean;
  showPrices?: boolean;
  /** Hide types no seat in the rendered map actually uses. */
  hideUnusedTypes?: boolean;
  headingSeatTypes?: string;
  headingAvailability?: string;
}

/** The swatch's viewBox edge; the seat glyph is drawn to fill it. */
const GLYPH_SIZE = 16;
const GLYPH_BODY = seatBodyPath(0, 0, GLYPH_SIZE, GLYPH_SIZE);

/** The selected swatch's frame width, and the core it leaves inside itself. */
const GLYPH_FRAME = seatSelectedFrame(GLYPH_SIZE, GLYPH_SIZE);
const GLYPH_CORE_SIZE = GLYPH_SIZE - GLYPH_FRAME * 2;
const GLYPH_CORE = seatBodyPath(0, 0, GLYPH_SIZE, GLYPH_SIZE, GLYPH_FRAME);

const GLYPH_OCCUPANT = seatOccupantPath(0, 0, GLYPH_SIZE, GLYPH_SIZE);
const GLYPH_OCCUPANT_STROKE = seatOccupantStroke(GLYPH_SIZE, GLYPH_SIZE);

/** The selected swatch's figure sits on the core, so it is drawn to the core. */
const GLYPH_CORE_OCCUPANT = seatOccupantPath(
  GLYPH_FRAME,
  GLYPH_FRAME,
  GLYPH_CORE_SIZE,
  GLYPH_CORE_SIZE,
);
const GLYPH_CORE_OCCUPANT_STROKE = seatOccupantStroke(GLYPH_CORE_SIZE, GLYPH_CORE_SIZE);

/**
 * A key for a seat map: its seat types on one side, its availability states on
 * the other.
 *
 * This ships in the library rather than being left to each application because
 * the swatch colors must come from the *same* resolution path as the seat
 * fills — `SeatType.color` when the document supplies one, the theme's
 * available color when it does not. Re-deriving that in application code is how
 * a legend ends up disagreeing with the map it describes.
 *
 * It is opt-in: `<KerusiSeatmap showLegend />` renders it inline, or use
 * `<KerusiLegend>` directly to place it anywhere.
 */
export function KerusiLegend({
  legend,
  locale = 'en',
  colors = DEFAULT_KERUSI_COLORS,
  typeColors = true,
  showPrices = true,
  hideUnusedTypes = true,
  headingSeatTypes = 'Seat types',
  headingAvailability = 'Availability',
}: KerusiLegendProps) {
  const types = legend.filter((entry) => !hideUnusedTypes || entry.seatCount > 0);
  const statuses = statusEntries(colors);

  return (
    <div className="kerusi-legend">
      {types.length > 0 && (
        <div className="kerusi-legend__block">
          <h4 className="kerusi-legend__heading">{headingSeatTypes}</h4>
          <ul className="kerusi-legend__list">
            {types.map((entry) => {
              const typeColor = (typeColors && entry.color) || null;
              const price = entry.price ? formatMoney(entry.price, locale) : '';
              return (
                <li key={entry.id} className="kerusi-legend__item">
                  <span
                    className="kerusi-legend__swatch"
                    aria-hidden="true"
                    style={{
                      background: typeColor ?? cssVar('availableBg', colors.availableBg),
                      // Mirrors `seatTextFill`: only a document-supplied color
                      // needs guessing at.
                      color: typeColor
                        ? readableOn(typeColor)
                        : cssVar('availableFg', colors.availableFg),
                    }}
                  />
                  <span className="kerusi-legend__label">{entry.label}</span>
                  {showPrices && price && <span className="kerusi-legend__price">{price}</span>}
                </li>
              );
            })}
          </ul>
        </div>
      )}

      <div className="kerusi-legend__block">
        <h4 className="kerusi-legend__heading">{headingAvailability}</h4>
        <ul className="kerusi-legend__list">
          {statuses.map((status) => (
            <li key={status.key} className="kerusi-legend__item">
              {/* Shape carries status now, so every swatch draws the seat glyph
                  rather than a flat colour — a flat swatch would teach a cue
                  the map itself no longer uses. */}
              <svg
                className="kerusi-legend__swatch kerusi-legend__swatch--glyph"
                aria-hidden="true"
                focusable="false"
                viewBox={`0 0 ${GLYPH_SIZE} ${GLYPH_SIZE}`}
              >
                <path d={GLYPH_BODY} style={{ fill: status.fill }} />
                {hasWash(status.kind) && (
                  <path
                    d={GLYPH_BODY}
                    style={{ fill: seatWashFill(status.kind, colors) }}
                    opacity="0.5"
                  />
                )}
                {status.kind === 'selected' && (
                  /* Two tones, same as the map: the body above is the frame,
                     this is the core inside it. */
                  <path d={GLYPH_CORE} style={{ fill: seatCoreFill(colors) }} />
                )}
                {hasOccupant(status.kind) && (
                  <path
                    d={status.kind === 'selected' ? GLYPH_CORE_OCCUPANT : GLYPH_OCCUPANT}
                    className={`kerusi-legend__occupant kerusi-legend__occupant--${status.kind}`}
                    strokeWidth={
                      status.kind === 'selected'
                        ? GLYPH_CORE_OCCUPANT_STROKE
                        : GLYPH_OCCUPANT_STROKE
                    }
                    style={{
                      fill: occupantFillFor(status.kind, colors),
                      stroke: occupantStrokeFor(status.kind, colors),
                    }}
                  />
                )}
              </svg>
              <span className="kerusi-legend__label">{status.label}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

// Colour means seat type; shape means status (see `seatFill`'s doc comment).
// Held and booked swatches share the plain "available" body colour — the map's
// colour there is always whatever the seat's own type supplies, which the
// legend has no single value for — and are told apart by their wash and
// occupant figure instead, same as on the map.
function statusEntries(colors: Required<KerusiSeatmapColors>): StatusEntry[] {
  const available = cssVar('availableBg', colors.availableBg);
  return [
    { key: 'available', label: 'Available', kind: 'plain', fill: available },
    {
      key: 'selected',
      label: 'Selected',
      kind: 'selected',
      fill: cssVar('selectedBg', colors.selectedBg),
    },
    { key: 'held', label: 'On hold', kind: 'held', fill: available },
    { key: 'booked', label: 'Booked', kind: 'booked', fill: available },
    {
      key: 'blocked',
      label: 'Blocked',
      kind: 'blocked',
      fill: cssVar('blockedBg', colors.blockedBg),
    },
  ];
}

function hasWash(kind: StatusKind): kind is 'held' | 'booked' {
  return kind === 'held' || kind === 'booked';
}

function hasOccupant(kind: StatusKind): kind is SeatOccupantVariant {
  return kind === 'selected' || kind === 'held' || kind === 'booked';
}
