// projects/react/src/kerusi-seatmap.tsx
import {
  buildNavigationGraph,
  buildRenderModel,
  DEFAULT_SEAT_ARIA_STRINGS,
  disallowedAnnouncement,
  computeSectionLayout,
  errorsOf,
  expireHolds as expireHoldsIn,
  formatMoney,
  isRtlLocale,
  KerusiValidationError,
  resolveColors,
  resolveMapLocale,
  seatAriaLabel,
  summarizeSelection,
  toggleSeatSelection,
  validateDocumentSet,
} from '@kerusiweb/core';
import type {
  KerusiState,
  KerusiViolation,
  Money,
  NavigationGraph,
  RenderMap,
  RenderSection,
  SectionLayout,
} from '@kerusiweb/core';
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useState } from 'react';
import type { KeyboardEvent as ReactKeyboardEvent } from 'react';
import { KerusiLegend } from './kerusi-legend.js';
import { KerusiSection } from './kerusi-section.js';
import type {
  KerusiSeatmapHandle,
  KerusiSeatmapProps,
  SeatInteraction,
  SectionRenderOptions,
} from './types.js';
import { useRovingFocus } from './use-roving-focus.js';

const NO_SELECTION: readonly string[] = [];
const DEFAULT_SELECTABLE_STATUSES = ['available'] as const;
const NO_OVERRIDES: Readonly<Record<string, SectionRenderOptions>> = {};

/**
 * Renders a Kerusi seat map.
 *
 * Takes a `KerusiMap` and its `KerusiState` directly — no adapter, no
 * intermediate row model. Each `Section` becomes its own `<svg>` with its own
 * layout mode and proportions, seats take their color from the map's legend,
 * every seat is keyboard-reachable and announced with its type, price, status
 * and §4.3.4 accessibility properties, and selection is an immutable list of
 * seat ids.
 *
 * ```tsx
 * <KerusiSeatmap map={map} state={state} selection={picked} onSelectionChange={setPicked} />
 * ```
 *
 * Import the stylesheet once, anywhere in the app:
 * `import '@kerusiweb/react/styles.css'`.
 */
export const KerusiSeatmap = forwardRef<KerusiSeatmapHandle, KerusiSeatmapProps>(
  function KerusiSeatmap(props, ref) {
    const {
      map,
      state,
      session,
      selection: controlledSelection,
      defaultSelection = NO_SELECTION,
      onSelectionChange,
      locale,
      rtl = 'auto',
      ariaStrings = DEFAULT_SEAT_ARIA_STRINGS,
      colors,
      typeColors = true,
      seatSize = 28,
      seatGap = 6,
      freeformBasis = 1000,
      unitScale = 1,
      showSectionLabels = true,
      showLegend = false,
      showLegendPrices = true,
      sectionIds,
      sectionOverrides = NO_OVERRIDES,
      selectableStatuses = DEFAULT_SELECTABLE_STATUSES,
      companionMode = 'auto',
      maxSelection,
      seatSelectable,
      interactive = true,
      expireHolds = false,
      expiryIntervalMs = 1000,
      validate = 'collect',
      onSeatSelect,
      onSeatDeselect,
      onSeatDisallowed,
      onSeatFocus,
      onValidationIssues,
      className,
      style,
      children,
    } = props;

    // --- selection: controlled or not ---------------------------------------

    const [uncontrolledSelection, setUncontrolledSelection] =
      useState<readonly string[]>(defaultSelection);
    const isControlled = controlledSelection !== undefined;
    const selection = isControlled ? controlledSelection : uncontrolledSelection;

    const commitSelection = useCallback(
      (next: readonly string[]) => {
        if (!isControlled) {
          setUncontrolledSelection(next);
        }
        onSelectionChange?.(next);
      },
      [isControlled, onSelectionChange],
    );

    // --- validation ---------------------------------------------------------

    const issues = useMemo<readonly KerusiViolation[]>(
      () => (validate === 'off' ? [] : validateDocumentSet({ map, state, session })),
      [validate, map, state, session],
    );

    useEffect(() => {
      if (validate !== 'off') {
        onValidationIssues?.(issues);
      }
      // `onValidationIssues` is deliberately absent: an inline callback would
      // re-announce the same issues on every render.
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [issues, validate]);

    if (validate === 'throw') {
      // Thrown during render, not from an effect, so a React error boundary
      // catches it — the idiomatic equivalent of the Angular binding's throw.
      const [first] = errorsOf(issues);
      if (first) {
        throw new KerusiValidationError(first.message, first.rule, first.id, issues);
      }
    }

    // --- derived model ------------------------------------------------------

    /** Bumped by the hold ticker to force the state to be re-derived. */
    const [expiryTick, setExpiryTick] = useState(0);

    useEffect(() => {
      if (!expireHolds) {
        return;
      }
      const handle = setInterval(() => setExpiryTick((n) => n + 1), expiryIntervalMs);
      return () => clearInterval(handle);
    }, [expireHolds, expiryIntervalMs]);

    /** The state actually rendered — with lapsed holds reverted when asked. */
    const effectiveState = useMemo<KerusiState | undefined>(() => {
      if (!state || !expireHolds) {
        return state;
      }
      // `expireHolds` returns the same object when nothing lapsed, so the
      // memos downstream of this one stay stable across a quiet tick.
      void expiryTick;
      return expireHoldsIn(state);
    }, [state, expireHolds, expiryTick]);

    const visibleSectionIds = useMemo<readonly string[] | undefined>(() => {
      const hidden = Object.entries(sectionOverrides)
        .filter(([, o]) => o.hidden)
        .map(([id]) => id);

      if (sectionIds) {
        return sectionIds.filter((id) => !hidden.includes(id));
      }
      if (hidden.length === 0) {
        return undefined;
      }
      return (map.sections ?? []).map((s) => s.id).filter((id) => !hidden.includes(id));
    }, [map, sectionIds, sectionOverrides]);

    const renderMap = useMemo<RenderMap>(
      () =>
        buildRenderModel(map, effectiveState, {
          locale,
          sectionIds: visibleSectionIds,
          selectableStatuses,
          seatSelectable,
        }),
      [map, effectiveState, locale, visibleSectionIds, selectableStatuses, seatSelectable],
    );

    const resolvedLocale = useMemo(() => resolveMapLocale(map, locale), [map, locale]);
    const isRtl = rtl === 'auto' ? isRtlLocale(resolvedLocale) : rtl === true;
    const resolvedColors = useMemo(() => resolveColors(colors), [colors]);
    const selectionSet = useMemo(() => new Set(selection), [selection]);

    /** Placed geometry per section, keyed by section id. */
    const layouts = useMemo<ReadonlyMap<string, SectionLayout>>(
      () =>
        new Map(
          renderMap.sections.map((section) => {
            const override = sectionOverrides[section.id] ?? {};
            return [
              section.id,
              computeSectionLayout(section, {
                seatSize: override.seatSize ?? seatSize,
                seatGap,
                freeformBasis,
                aspectRatio: override.aspectRatio,
                rtl: isRtl,
              }),
            ];
          }),
        ),
      [renderMap, sectionOverrides, seatSize, seatGap, freeformBasis, isRtl],
    );

    /** Navigation graphs per section — arrows move within, Tab moves between. */
    const graphs = useMemo<ReadonlyMap<string, NavigationGraph>>(
      () =>
        new Map(
          renderMap.sections.map((section) => [
            section.id,
            buildNavigationGraph(section, { rtl: isRtl }),
          ]),
        ),
      [renderMap, isRtl],
    );

    const ariaLabels = useMemo<ReadonlyMap<string, string>>(
      () =>
        new Map(
          [...renderMap.seatsById.values()].map((seat) => [
            seat.id,
            seatAriaLabel(seat, resolvedLocale, ariaStrings),
          ]),
        ),
      [renderMap, resolvedLocale, ariaStrings],
    );

    // --- focus and announcements --------------------------------------------

    const { focusedSeatIds, setFocusedSeat, moveFocusTo, focusSeat, registerSeat } =
      useRovingFocus(renderMap);

    /**
     * The live-region text, plus a counter that makes a repeat of the same
     * message textually distinct.
     *
     * A live region that sees no text change stays silent, so announcing the
     * same thing twice — picking two seats and hearing "1 seat selected" both
     * times — needs the second one to differ somehow. The Angular binding
     * clears the region and refills it a microtask later; two commits, which
     * React would batch back into one unless deliberately escaped. Appending a
     * zero-width space on alternate announcements does the same job in a single
     * commit: the text differs, and no screen reader speaks the character.
     */
    const [announcement, setAnnouncement] = useState({ message: '', nonce: 0 });

    const announce = useCallback((message: string) => {
      setAnnouncement((current) => ({ message, nonce: current.nonce + 1 }));
    }, []);

    const liveMessage =
      announcement.nonce % 2 === 0 ? announcement.message : `${announcement.message}\u200b`;

    const announceSelection = useCallback(
      (next: readonly string[]) => {
        if (next.length === 0) {
          announce(ariaStrings.selectionEmpty);
          return;
        }
        const { total } = summarizeSelection(renderMap, next);
        announce(ariaStrings.selectionSummary(next.length, formatTotal(total, resolvedLocale)));
      },
      [announce, ariaStrings, renderMap, resolvedLocale],
    );

    // --- interaction --------------------------------------------------------

    const onSeatActivate = useCallback(
      (seatId: string) => {
        const seat = renderMap.seatsById.get(seatId);
        if (!seat) {
          return;
        }

        const outcome = toggleSeatSelection(selection, seatId, {
          seatsById: renderMap.seatsById,
          companionMode,
          maxSelection,
        });

        if (outcome.kind === 'disallowed') {
          announce(disallowedAnnouncement(seat, outcome.reason!, ariaStrings));
          onSeatDisallowed?.({ seat, reason: outcome.reason! });
          return;
        }

        commitSelection(outcome.selection);
        const event: SeatInteraction = {
          seat,
          selection: outcome.selection,
          changed: outcome.changed,
        };
        (outcome.kind === 'select' ? onSeatSelect : onSeatDeselect)?.(event);
        announceSelection(outcome.selection);
      },
      [
        renderMap,
        selection,
        companionMode,
        maxSelection,
        announce,
        ariaStrings,
        onSeatDisallowed,
        commitSelection,
        onSeatSelect,
        onSeatDeselect,
        announceSelection,
      ],
    );

    const onSeatFocused = useCallback(
      (seatId: string) => {
        const seat = renderMap.seatsById.get(seatId);
        if (!seat) {
          return;
        }
        setFocusedSeat(seat.sectionId, seatId);
        onSeatFocus?.(seat);
      },
      [renderMap, setFocusedSeat, onSeatFocus],
    );

    /**
     * Arrow keys walk the navigation graph, which orders seats by `col` in grid
     * and mixed sections — §4.3.1's logical adjacency — so the aisle that is a
     * skipped column is stepped across rather than into.
     */
    const onKeyDown = useCallback(
      (sectionId: string, event: ReactKeyboardEvent<SVGGElement>) => {
        const seatId = (event.target as HTMLElement | null)?.dataset?.['seatId'];
        if (!seatId) {
          return;
        }

        const graph = graphs.get(sectionId);
        if (!graph) {
          return;
        }
        const neighbours = graph.neighbours.get(seatId);

        let target: string | undefined;
        switch (event.key) {
          case 'ArrowLeft':
            target = neighbours?.left;
            break;
          case 'ArrowRight':
            target = neighbours?.right;
            break;
          case 'ArrowUp':
            target = neighbours?.up;
            break;
          case 'ArrowDown':
            target = neighbours?.down;
            break;
          case 'Home':
            target = event.ctrlKey ? graph.first : neighbours?.rowStart;
            break;
          case 'End':
            target = event.ctrlKey ? graph.last : neighbours?.rowEnd;
            break;
          case 'PageUp':
            target = graph.first;
            break;
          case 'PageDown':
            target = graph.last;
            break;
          case 'Enter':
          case ' ':
            event.preventDefault();
            onSeatActivate(seatId);
            return;
          case 'Escape':
            if (selection.length > 0) {
              event.preventDefault();
              commitSelection([]);
              announceSelection([]);
            }
            return;
          default:
            return;
        }

        if (target) {
          event.preventDefault();
          moveFocusTo(sectionId, target);
        }
      },
      [graphs, onSeatActivate, selection, commitSelection, announceSelection, moveFocusTo],
    );

    // --- public handle ------------------------------------------------------

    const summary = useMemo(() => summarizeSelection(renderMap, selection), [renderMap, selection]);

    useImperativeHandle(ref, () => ({ summary, focusSeat }), [summary, focusSeat]);

    // --- render -------------------------------------------------------------

    const labelFor = (section: RenderSection): string | undefined =>
      sectionOverrides[section.id]?.label ?? section.label;
    const labelId = (section: RenderSection): string =>
      `kerusi-section-${renderMap.id}-${section.id}`;

    return (
      <div
        className={className ? `kerusi-seatmap ${className}` : 'kerusi-seatmap'}
        role="group"
        aria-label={renderMap.name ?? `Seat map ${renderMap.id}`}
        dir={isRtl ? 'rtl' : undefined}
        lang={resolvedLocale}
        style={style}
      >
        {renderMap.sections.map((section) => {
          const label = labelFor(section);
          return (
            <section
              key={section.id}
              className={`kerusi-seatmap__section kerusi-seatmap__section--${section.layoutMode}`}
              role="group"
              aria-labelledby={label ? labelId(section) : undefined}
              aria-label={label ? undefined : section.id}
            >
              {showSectionLabels && label && (
                <h3 className="kerusi-section-label" id={labelId(section)}>
                  {label}
                </h3>
              )}

              <KerusiSection
                section={section}
                layout={layouts.get(section.id)!}
                selection={selectionSet}
                focusedSeatId={focusedSeatIds[section.id] ?? null}
                ariaLabels={ariaLabels}
                colors={resolvedColors}
                typeColors={typeColors}
                unitScale={unitScale}
                interactive={interactive}
                onSeatActivate={onSeatActivate}
                onSeatFocused={onSeatFocused}
                onSeatKeyDown={(event) => onKeyDown(section.id, event)}
                registerSeat={registerSeat}
              />
            </section>
          );
        })}

        {showLegend && (
          <KerusiLegend
            legend={renderMap.legend}
            locale={resolvedLocale}
            colors={resolvedColors}
            typeColors={typeColors}
            showPrices={showLegendPrices}
          />
        )}

        <p className="kerusi-sr-only" aria-live="polite" aria-atomic="true">
          {liveMessage}
        </p>

        {children}
      </div>
    );
  },
);

function formatTotal(total: Money | undefined, locale: string): string {
  return total ? formatMoney(total, locale) : '';
}

// projects/ngx-kerusi-seatmap/src/lib/kerusi-seatmap/kerusi-seatmap.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  model,
  output,
  signal,
} from '@angular/core';
import {
  buildNavigationGraph,
  buildRenderModel,
  computeSectionLayout,
  DEFAULT_SEAT_ARIA_STRINGS,
  DisallowedReason,
  disallowedAnnouncement,
  errorsOf,
  expireHolds,
  formatMoney,
  isRtlLocale,
  KerusiMap,
  KerusiSeatmapColors,
  KerusiSession,
  KerusiState,
  KerusiValidationError,
  KerusiViolation,
  Money,
  NavigationGraph,
  RenderMap,
  RenderSeat,
  RenderSection,
  resolveColors,
  resolveMapLocale,
  SeatAriaStrings,
  seatAriaLabel,
  SeatRenderStatus,
  SectionLayout,
  summarizeSelection,
  toggleSeatSelection,
  validateDocumentSet,
} from '@kerusiweb/core';
import { KerusiSectionComponent } from './kerusi-section.component';
import { KerusiLegendComponent } from './kerusi-legend.component';

/** How a document with validation errors is handled. */
export type ValidationMode =
  /** Report through `validationIssues` and render anyway. The default. */
  | 'collect'
  /** Throw a `KerusiValidationError`, as `validateKerusiMap` does. */
  | 'throw'
  /** Skip validation entirely, for a document validated upstream. */
  | 'off';

/** Per-section rendering overrides, keyed by `Section.id`. */
export interface SectionRenderOptions {
  hidden?: boolean;
  /** Overrides `Section.aspectRatio`. */
  aspectRatio?: string;
  /** Overrides the seat size for this section only. */
  seatSize?: number;
  /** Overrides the localized `Section.label`. */
  label?: string;
}

/** What a seat event carries. Everything the document knows, already resolved. */
export interface SeatInteraction {
  seat: RenderSeat;
  /** The selection after this event. */
  selection: readonly string[];
  /** Seats whose membership changed, including companions (§4.6). */
  changed: readonly string[];
}

export interface SeatDisallowed {
  seat: RenderSeat;
  reason: DisallowedReason;
}

/**
 * Renders a Kerusi seat map.
 *
 * Takes a `KerusiMap` and its `KerusiState` directly — no adapter, no
 * intermediate row model. Each `Section` becomes its own `<svg>` with its own
 * layout mode and proportions, seats take their color from the map's legend,
 * every seat is keyboard-reachable and announced with its type, price, status
 * and §4.3.4 accessibility properties, and selection is an immutable set of
 * seat ids the caller can two-way bind.
 *
 * ```html
 * <kerusi-seatmap [map]="map" [state]="state" [(selection)]="picked" />
 * ```
 */
@Component({
  selector: 'kerusi-seatmap',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [KerusiSectionComponent, KerusiLegendComponent],
  templateUrl: './kerusi-seatmap.component.html',
  styleUrl: './kerusi-seatmap.component.css',
})
export class KerusiSeatmapComponent {
  private readonly host = inject(ElementRef<HTMLElement>);

  // --- documents ------------------------------------------------------------

  readonly map = input.required<KerusiMap>();
  readonly state = input<KerusiState | undefined>(undefined);
  /** The optional map↔event join (§5.3). Validated against the map and state. */
  readonly session = input<KerusiSession | undefined>(undefined);

  // --- selection ------------------------------------------------------------

  /** Selected seat ids. Two-way: `[(selection)]`, or read-only with `[selection]`. */
  readonly selection = model<readonly string[]>([]);

  // --- localization ---------------------------------------------------------

  /** Overrides `KerusiMap.locale` (BCP-47). */
  readonly locale = input<string | undefined>(undefined);
  /** Right-to-left rendering. `auto` derives it from the resolved locale. */
  readonly rtl = input<boolean | 'auto'>('auto');
  /** Overrides the built-in English announcement strings. */
  readonly ariaStrings = input<SeatAriaStrings>(DEFAULT_SEAT_ARIA_STRINGS);

  // --- appearance -----------------------------------------------------------

  readonly colors = input<KerusiSeatmapColors>({});
  /** Let an available seat take its `SeatType.color` (§4.7). */
  readonly typeColors = input<boolean>(true);
  /** Grid cell edge, in viewBox units. */
  readonly seatSize = input<number>(28);
  /** Gap between grid cells, in viewBox units. */
  readonly seatGap = input<number>(6);
  /** Freeform viewBox width; height follows the section's aspect ratio. */
  readonly freeformBasis = input<number>(1000);
  /**
   * CSS pixels per viewBox unit. Caps each section at its natural size so a
   * narrow section and a wide one in the same map draw seats the same size.
   */
  readonly unitScale = input<number>(1);
  readonly showSectionLabels = input<boolean>(true);
  readonly showLegend = input<boolean>(false);
  readonly showLegendPrices = input<boolean>(true);

  // --- section control ------------------------------------------------------

  /** Render only these sections, in this order. Default: all, by `Section.index`. */
  readonly sectionIds = input<readonly string[] | undefined>(undefined);
  readonly sectionOverrides = input<Readonly<Record<string, SectionRenderOptions>>>({});

  // --- interaction ----------------------------------------------------------

  /** Statuses in which a seat may be picked. Default: `['available']`. */
  readonly selectableStatuses = input<readonly SeatRenderStatus[]>(['available']);
  /** `auto` selects a seat's companion closure together (§4.6). */
  readonly companionMode = input<'auto' | 'independent'>('auto');
  readonly maxSelection = input<number | undefined>(undefined);
  /** A final say on selectability, applied after the status test. */
  readonly seatSelectable = input<((seat: RenderSeat) => boolean) | undefined>(undefined);
  /** When false the map renders read-only: no pointer or keyboard interaction. */
  readonly interactive = input<boolean>(true);
  /**
   * Revert a lapsed `holdExpires` to available on a ticker (§5.1). Off by
   * default — a renderer should stay passive unless asked.
   */
  readonly expireHolds = input<boolean>(false);
  readonly expiryIntervalMs = input<number>(1000);

  // --- validation -----------------------------------------------------------

  readonly validate = input<ValidationMode>('collect');

  // --- outputs --------------------------------------------------------------

  readonly seatSelect = output<SeatInteraction>();
  readonly seatDeselect = output<SeatInteraction>();
  readonly seatDisallowed = output<SeatDisallowed>();
  readonly seatFocus = output<RenderSeat>();
  /** Emitted whenever the documents change, in `collect` mode. */
  readonly validationIssues = output<readonly KerusiViolation[]>();

  // --- internal state -------------------------------------------------------

  /**
   * The seat holding each section's tab stop, keyed by section id.
   *
   * Per section, not per map: arrow keys never cross a section boundary, so a
   * single map-wide tab stop would leave every section after the first
   * unreachable by keyboard. Tab moves between sections, arrows move within.
   */
  private readonly focusedSeatIds = signal<Readonly<Record<string, string>>>({});
  private readonly announcement = signal('');
  /** Bumped by the hold ticker to force the state to be re-derived. */
  private readonly expiryTick = signal(0);

  constructor() {
    effect(() => {
      const issues = this.issues();
      if (this.validate() !== 'off') {
        this.validationIssues.emit(issues);
      }
      if (this.validate() === 'throw') {
        const [first] = errorsOf(issues);
        if (first) {
          throw new KerusiValidationError(first.message, first.rule, first.id, issues);
        }
      }
    });

    // Keep every section's tab stop pointing at a seat that still exists.
    effect(() => {
      const model = this.renderMap();
      const current = this.focusedSeatIds();
      const next: Record<string, string> = {};
      let changed = Object.keys(current).length !== model.sections.length;

      for (const section of model.sections) {
        const held = current[section.id];
        const valid = held && section.seats.some((seat) => seat.id === held);
        const resolved = valid ? held : section.seats[0]?.id;
        if (resolved) {
          next[section.id] = resolved;
          changed ||= resolved !== held;
        }
      }

      if (changed) {
        this.focusedSeatIds.set(next);
      }
    });

    effect((onCleanup) => {
      if (!this.expireHolds()) {
        return;
      }
      const handle = setInterval(
        () => this.expiryTick.update((n) => n + 1),
        this.expiryIntervalMs(),
      );
      onCleanup(() => clearInterval(handle));
    });
  }

  // --- derived model --------------------------------------------------------

  protected readonly issues = computed<readonly KerusiViolation[]>(() =>
    this.validate() === 'off'
      ? []
      : validateDocumentSet({
          map: this.map(),
          state: this.state(),
          session: this.session(),
        }),
  );

  /** The state actually rendered — with lapsed holds reverted when asked. */
  private readonly effectiveState = computed<KerusiState | undefined>(() => {
    const state = this.state();
    if (!state || !this.expireHolds()) {
      return state;
    }
    this.expiryTick();
    return expireHolds(state);
  });

  protected readonly renderMap = computed<RenderMap>(() =>
    buildRenderModel(this.map(), this.effectiveState(), {
      locale: this.locale(),
      sectionIds: this.visibleSectionIds(),
      selectableStatuses: this.selectableStatuses(),
      seatSelectable: this.seatSelectable(),
    }),
  );

  protected readonly resolvedLocale = computed(() => resolveMapLocale(this.map(), this.locale()));

  protected readonly isRtl = computed(() =>
    this.rtl() === 'auto' ? isRtlLocale(this.resolvedLocale()) : this.rtl() === true,
  );

  protected readonly resolvedColors = computed<Required<KerusiSeatmapColors>>(() =>
    resolveColors(this.colors()),
  );

  protected readonly selectionSet = computed(() => new Set(this.selection()));

  /** Placed geometry per section, keyed by section id. */
  protected readonly layouts = computed<ReadonlyMap<string, SectionLayout>>(() => {
    const overrides = this.sectionOverrides();
    return new Map(
      this.renderMap().sections.map((section) => {
        const override = overrides[section.id] ?? {};
        return [
          section.id,
          computeSectionLayout(section, {
            seatSize: override.seatSize ?? this.seatSize(),
            seatGap: this.seatGap(),
            freeformBasis: this.freeformBasis(),
            aspectRatio: override.aspectRatio,
            rtl: this.isRtl(),
          }),
        ];
      }),
    );
  });

  /** Navigation graphs per section — arrows move within, Tab moves between. */
  private readonly graphs = computed<ReadonlyMap<string, NavigationGraph>>(
    () =>
      new Map(
        this.renderMap().sections.map((section) => [
          section.id,
          buildNavigationGraph(section, { rtl: this.isRtl() }),
        ]),
      ),
  );

  protected readonly ariaLabels = computed<ReadonlyMap<string, string>>(() => {
    const locale = this.resolvedLocale();
    const strings = this.ariaStrings();
    return new Map(
      [...this.renderMap().seatsById.values()].map((seat) => [
        seat.id,
        seatAriaLabel(seat, locale, strings),
      ]),
    );
  });

  protected readonly mapLabel = computed(
    () => this.renderMap().name ?? `Seat map ${this.renderMap().id}`,
  );

  /** Live-region text: the running selection, or the last disallowed reason. */
  protected readonly liveMessage = computed(() => this.announcement());

  /** The selection's seats and total, for callers that want it off the template. */
  readonly summary = computed(() => summarizeSelection(this.renderMap(), this.selection()));

  // --- template helpers -----------------------------------------------------

  protected layoutFor(section: RenderSection): SectionLayout {
    return this.layouts().get(section.id)!;
  }

  protected labelFor(section: RenderSection): string | undefined {
    return this.sectionOverrides()[section.id]?.label ?? section.label;
  }

  protected labelId(section: RenderSection): string {
    return `kerusi-section-${this.renderMap().id}-${section.id}`;
  }

  /** The seat holding this section's tab stop. */
  protected focusedSeatIn(section: RenderSection): string | null {
    return this.focusedSeatIds()[section.id] ?? null;
  }

  // --- interaction ----------------------------------------------------------

  protected onSeatActivate(seatId: string): void {
    const model = this.renderMap();
    const seat = model.seatsById.get(seatId);
    if (!seat) {
      return;
    }

    const outcome = toggleSeatSelection(this.selection(), seatId, {
      seatsById: model.seatsById,
      companionMode: this.companionMode(),
      maxSelection: this.maxSelection(),
    });

    if (outcome.kind === 'disallowed') {
      this.announce(disallowedAnnouncement(seat, outcome.reason!, this.ariaStrings()));
      this.seatDisallowed.emit({ seat, reason: outcome.reason! });
      return;
    }

    this.selection.set(outcome.selection);
    const event: SeatInteraction = {
      seat,
      selection: outcome.selection,
      changed: outcome.changed,
    };
    (outcome.kind === 'select' ? this.seatSelect : this.seatDeselect).emit(event);
    this.announceSelection(outcome.selection);
  }

  protected onSeatFocused(seatId: string): void {
    const seat = this.renderMap().seatsById.get(seatId);
    if (!seat) {
      return;
    }
    this.setFocusedSeat(seat.sectionId, seatId);
    this.seatFocus.emit(seat);
  }

  /**
   * Arrow keys walk the navigation graph, which orders seats by `col` in grid
   * and mixed sections — §4.3.1's logical adjacency — so the aisle that is a
   * skipped column is stepped across rather than into.
   */
  protected onKeydown(section: RenderSection, event: KeyboardEvent): void {
    const seatId = (event.target as HTMLElement)?.dataset?.['seatId'];
    if (!seatId) {
      return;
    }

    const graph = this.graphs().get(section.id);
    const neighbours = graph?.neighbours.get(seatId);
    if (!graph) {
      return;
    }

    let target: string | undefined;
    switch (event.key) {
      case 'ArrowLeft':
        target = neighbours?.left;
        break;
      case 'ArrowRight':
        target = neighbours?.right;
        break;
      case 'ArrowUp':
        target = neighbours?.up;
        break;
      case 'ArrowDown':
        target = neighbours?.down;
        break;
      case 'Home':
        target = event.ctrlKey ? graph.first : neighbours?.rowStart;
        break;
      case 'End':
        target = event.ctrlKey ? graph.last : neighbours?.rowEnd;
        break;
      case 'PageUp':
        target = graph.first;
        break;
      case 'PageDown':
        target = graph.last;
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        this.onSeatActivate(seatId);
        return;
      case 'Escape':
        if (this.selection().length > 0) {
          event.preventDefault();
          this.selection.set([]);
          this.announceSelection([]);
        }
        return;
      default:
        return;
    }

    if (target) {
      event.preventDefault();
      this.moveFocusTo(section.id, target);
    }
  }

  private setFocusedSeat(sectionId: string, seatId: string): void {
    if (this.focusedSeatIds()[sectionId] === seatId) {
      return;
    }
    this.focusedSeatIds.update((all) => ({ ...all, [sectionId]: seatId }));
  }

  /**
   * Moves the roving tab stop, then the DOM focus that follows it.
   *
   * Seat ids come from the document, so they cannot be interpolated into a
   * selector unescaped — and `CSS.escape` is absent in jsdom and under SSR.
   * Scanning the rendered nodes avoids both problems.
   */
  private moveFocusTo(sectionId: string, seatId: string): void {
    this.setFocusedSeat(sectionId, seatId);
    const nodes = (this.host.nativeElement as HTMLElement).querySelectorAll<SVGGElement>(
      '[data-seat-id]',
    );
    for (const node of Array.from(nodes)) {
      if (node.dataset['seatId'] === seatId) {
        node.focus?.();
        return;
      }
    }
  }

  private announceSelection(selection: readonly string[]): void {
    const strings = this.ariaStrings();
    if (selection.length === 0) {
      this.announce(strings.selectionEmpty);
      return;
    }
    const { total } = summarizeSelection(this.renderMap(), selection);
    this.announce(
      strings.selectionSummary(selection.length, formatTotal(total, this.resolvedLocale())),
    );
  }

  private announce(message: string): void {
    // Re-announce an identical message by clearing first; a live region that
    // sees no text change stays silent.
    this.announcement.set('');
    queueMicrotask(() => this.announcement.set(message));
  }

  private visibleSectionIds(): readonly string[] | undefined {
    const explicit = this.sectionIds();
    const overrides = this.sectionOverrides();
    const hidden = Object.entries(overrides)
      .filter(([, o]) => o.hidden)
      .map(([id]) => id);

    if (explicit) {
      return explicit.filter((id) => !hidden.includes(id));
    }
    if (hidden.length === 0) {
      return undefined;
    }
    return (this.map().sections ?? []).map((s) => s.id).filter((id) => !hidden.includes(id));
  }
}

function formatTotal(total: Money | undefined, locale: string): string {
  return total ? formatMoney(total, locale) : '';
}
